### ISSUE TITLE
Dev versions uploaded to modrinth

### ISSUE THREAD

**Issue by AlexIIL** [Mysterious-Dev/Quilt-Tag-Plus#3]
### Version of Minecraft

1.19.4

### Version of the mod

0.1.3

### Description of the bug

This is a problem because the dev jar isn't remapped.

This causes crashes like this: [latest.log](https://github.com/Mysterious-Dev/Quilt-Tag-Plus/files/11961449/message-2023-07-05-discord-1.txt)

This affects a lot of recent versions - I'm not sure exactly what the fix is. I think in the gradle task you need to change the `uploadFIle` to use `remapJar`? I'm not certain though, I'd recommend testing locally.

https://github.com/Mysterious-Dev/Quilt-Tag-Plus/blob/1fdc7feb5c94883455cec9854193f3e16fc44164/build.gradle#L13

**Comment by Mysterious-Dev** [comment]
Sorry for the delay. It's fixed with [0.1.4](https://modrinth.com/mod/quilt-tag-plus/version/0.1.4+1.19.4) for 1.19.4 and [0.2.2](https://modrinth.com/mod/quilt-tag-plus/version/0.2.2+1.20.1) for 1.20.1.
